include_recipe 'apt::default' # noop on nodes that do not support apt
include_recipe 'sanity::ipv6'
include_recipe 'sanity::timezone'
include_recipe 'sanity::resolver'
include_recipe 'sanity::packages'
include_recipe 'sanity::openssh'
include_recipe 'sanity::iptables'
include_recipe 'sanity::check_connectivity'
include_recipe 'sanity::mta'
include_recipe 'sanity::aliases'
include_recipe 'sanity::apt_sources'
include_recipe 'sanity::apt_clean'
include_recipe 'sanity::unattended_upgrades'
include_recipe 'sanity::auto_reboot'
include_recipe 'sanity::monit'
include_recipe 'sanity::nginx'
include_recipe 'sanity::vrms'
