---
driver:
  name: dokken
  privileged: true # allows systemd services to start
  chef_image: cincproject/cinc
  chef_version: <%= ENV.fetch('CHEF_VERSION', 18) %>

provisioner:
  name: dokken
  product_name: cinc
  chef_binary: /opt/cinc/bin/cinc-client
  deprecations_as_errors: true
  multiple_converge: 2

transport:
  name: dokken

verifier:
  name: inspec
  inspec_tests:
    - git: https://github.com/dev-sec/linux-baseline
    - git: https://github.com/dev-sec/linux-patch-baseline
    - git: https://github.com/dev-sec/ssh-baseline

platforms:
  # @see https://github.com/chef-cookbooks/testing_examples/blob/main/kitchen.dokken.yml
  # @see https://hub.docker.com/u/dokken
  - name: debian-11
    driver:
      image: dokken/debian-11
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get upgrade -y
        - RUN /usr/bin/apt-get purge exim4* -y
    verifier:
      inspec_tests:
        - path: profile/controls
      input_files:
        - test/integration/default/inspec/input_files/control-waivers-debian-11.yml
  - name: debian-12
    driver:
      image: dokken/debian-12
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get upgrade -y
        - RUN /usr/bin/apt-get purge exim4* -y
    verifier:
      inspec_tests:
        - path: profile/controls
      input_files:
        - test/integration/default/inspec/input_files/control-waivers-debian-12.yml
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get upgrade -y
    verifier:
      inspec_tests:
        - path: profile/controls
      input_files:
        - test/integration/default/inspec/input_files/control-waivers-ubuntu-2204.yml

suites:
  - name: default
    run_list:
      - recipe[sanity::default]
    attributes:
      monit: { config: { start_delay: 0 } } # start Monit immediately to run tests
      ssh-hardening: { ssh: { server: {
        # allow ecdh-sha2-nistp521 (UNSECURE) so inspec can log in to run control specs
        # allow curve25519-sha256@libssh.org so we can log in with `kitchen login`
        kex: "ecdh-sha2-nistp521,curve25519-sha256@libssh.org"
      } } }
      sanity:
        firewall: { type: <%= ENV.fetch('FIREWALL_TYPE', 'nftables') %> }
        ssh: { authorized_keys: ["ssh-ed25519 AAAA+testkey test@example.net"] }
        ipv6: false # XXX: no IPv6 connectivity available with dokken
        root_email: test@example.local
