---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: debian/stretch64
  - name: centos/7

suites:
  - name: default
    run_list:
      - recipe[sanity::default]
    attributes:
      sanity:
        ipv6: false
        ssh:
          authorized_keys: ["ssh-rsa bogguskey test@example.net"]
