---
driver:
  name: dokken
  privileged: true
  chef_version: 14

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  multiple_converge: 2
  # enforce_idempotency: true # TODO

verifier:
  name: inspec

platforms:
  - name: debian-10
    driver:
      image: debian:10
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y lsb-release systemd procps

suites:
  - name: default
    run_list:
      - recipe[sanity::default]
    attributes:
      monit: { config: { start_delay: 0 } } # start Monit immediately to run tests
      sanity:
        firewall: iptables
        ipv6: false
        ssh: { authorized_keys: ["ssh-rsa bogguskey test@example.net"] }
