---
# https://github.com/test-kitchen/kitchen-dokken/blob/main/documentation/PODMAN.md
driver:
  name: dokken
  privileged: true  # allows systemd services to start
  chef_version: 16

provisioner:
  name: dokken
  deprecations_as_errors: true
  multiple_converge: 2
  # enforce_idempotency: true # TODO: but blocked by Monit cookbook

transport:
  name: dokken

verifier:
  name: inspec # XXX: cinc-auditor actually
  inspec_tests:
    - git: https://github.com/dev-sec/linux-baseline
    - git: https://github.com/dev-sec/linux-patch-baseline
    - git: https://github.com/dev-sec/ssh-baseline
    - git: https://github.com/dev-sec/ssl-baseline
  input_files:
    - test/integration/control-waivers.yml

platforms:
  # @see https://github.com/chef-cookbooks/testing_examples/blob/main/kitchen.dokken.yml
  # @see https://hub.docker.com/u/dokken
  - name: debian-11
    driver:
      image: dokken/debian-11
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get upgrade -y
  - name: debian-10
    driver:
      image: dokken/debian-10
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get upgrade -y


suites:
  - name: default
    run_list:
      - recipe[sanity::default]
    attributes:
      monit: { config: { start_delay: 0 } } # start Monit immediately to run tests
      sanity:
        ssh: { authorized_keys: ["ssh-ed25519 AAAA+testkey test@example.net"] }
