---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'libvirt' %>

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: debian/stretch64
  - name: centos/7

suites:
  - name: default
    run_list:
      - recipe[sanity::default]
    attributes:
      monit: { config: { start_delay: 0 } } # start Monit immediately to run tests
      sanity:
        ipv6: false
        ssh: { authorized_keys: ["ssh-rsa bogguskey test@example.net"] }
