AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Layout/LineLength:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'profile/**/*'
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"

Style/RedundantConstantBase:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
