AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
