name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 0 1 * *" # first day of every month

permissions:
  contents: read

jobs:
  kitchen:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ["default-debian-13", "default-debian-12", "default-ubuntu-2204"]
        firewall-type: ["nftables", "iptables"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Test Kitchen suite ${{ matrix.suite }}
        run: env FIREWALL_TYPE=${{ matrix.firewall-type }} bundle exec rake kitchen:${{ matrix.suite }}
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run style checks
        run: bundle exec rake style:ruby
